#!/bin/bash

# Message broker configuration.
# May also used to initialize other parts of cHaTTP

export CHATTP_WEBAPP_ADDR="/dummy/path"
export CHATTP_WEBAPP_FAMILY="UNIX"
export CHATTP_WEBAPP_PORT=""

export CHATTP_MESG_RELAY_ADDR="/dummy/path2"
export CHATTP_MESG_RELAY_FAMILY="UNIX"
export CHATTP_MESG_RELAY_PORT=""

export CHATTP_PERSISTENCE_LAYER_ADDR="/dummy/path3"
export CHATTP_PERSISTENCE_LAYER_FAMILY="UNIX"
export CHATTP_PERSISTENCE_LAYER_PORT=""

export CHATTP_MSGBROKER_MSGRELAY_BIND_ADDR="/dummy/path4"
export CHATTP_MSGBROKER_MSGRELAY_BIND_PORT=""

export CHATTP_MSGBROKER_PERSISTENCE_BIND_ADDR="/dummy/path5"
export CHATTP_MSGBROKER_PERSISTENCE_BIND_PORT=""

export CHATTP_MSGBROKER_WEBAPP_BIND_ADDR="/dummy/path6"
export CHATTP_MSGBROKER_WEBAPP_BIND_PORT=""
